spring:
  messages:
    basename: "i18n/appmessages"
    encoding: "UTF-8"

application:
  defaultLocale: en_US
  io:
    max_attempts: 10
  availableLocales:
    - ru_RU
    - en_US

test:
  fileNames:
    ru_RU: "ru_questions.csv"
    en_US: "en_questions.csv"

  rightAnswersCountToPass: 3